import Link from "@material-ui/icons/Link";
import LinkOff from "@material-ui/icons/LinkOff";
import NoteAdd from "@material-ui/icons/NoteAdd";
import BackspaceIcon from "@material-ui/icons/Backspace";
import MenuIcon from "@material-ui/icons/Menu";
import WbSunny from "@material-ui/icons/WbSunny";
import NightsStay from "@material-ui/icons/NightsStay";
import HomeIcon from "@material-ui/icons/Home";
import WorkIcon from "@material-ui/icons/Work";
import CategoryIcon from "@material-ui/icons/Category";
import Settings from "@material-ui/icons/Settings";
import LockOpenIcon from "@material-ui/icons/LockOpen";
import LockIcon from "@material-ui/icons/Lock";

export const LinkEnabledIcon = () => <Link />;
export const LinkDisabledIcon = () => <LinkOff />;
export const CreateIcon = () => <NoteAdd />;
export const StripIcon = () => <BackspaceIcon />;
export const MenuToggleIcon = () => <MenuIcon />;
export const LightModeIcon = () => <WbSunny />;
export const DarkModeIcon = () => <NightsStay />;
export const HomePageIcon = () => <HomeIcon />;
export const ExperienceIcon = () => <WorkIcon />;
export const ProjectsIcon = () => <CategoryIcon />;
export const SettingsIcon = () => <Settings />;
export const LoginIcon = () => <LockOpenIcon />;
export const LogoutIcon = () => <LockIcon />;
